[platformio]
default_envs = cyd_usb
src_dir = src
include_dir = include

[common]
platform  = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board     = esp32dev
framework = arduino

; Verhindert das Schalten der RTS-Leitung (steuert den RST/EN-Pin an) -> kein Hard-Reset beim Oeffnen des Monitors
monitor_rts = 0
; Verhindert das Schalten der DTR-Leitung (steuert GPIO0 an) -> verhindert ungewollten Wechsel in den Bootloader-Modus
monitor_dtr = 0

board_build.flash_size  = 4MB
board_upload.flash_size = 4MB

monitor_speed = 500000
lib_ldf_mode  = deep+

lib_deps =
    adafruit/Adafruit ST7735 and ST7789 Library @ 1.11.0
    adafruit/Adafruit GFX Library @ 1.12.6
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#f956c5d8ce3bf39169c7378416b89e7cfe70a034
    bblanchon/ArduinoJson @ 7.4.3

build_flags =
    -O3
    -DCORE_DEBUG_LEVEL=0
    -I "${platformio.packages_dir}/framework-arduinoespressif32/libraries/Network/src"
    -DARDUINO_ARCH_ESP32
    -DBOARD_CYD
    -DOTA_PASSWORD=\"dasdaDadaDAsdsadaDASdd\"
    -I include
    -I include/Fonts
    -Wno-deprecated-declarations
    -Wno-write-strings
    -w

[env:cyd_usb]
extends         = common
upload_protocol = esptool
upload_speed    = 921600

[env:cyd_ota]
extends         = common
upload_protocol = espota
upload_port     = 192.168.0.43
upload_flags =
    --port=3232
    --auth=dasdaDadaDAsdsadaDASdd
